import os
import json
import spacy
import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional

# spacy multithreading bei mehreren requests

def check_packages():
    try:
        nlps = {}
        nlps["de"] = spacy.load("de_core_news_sm")
        nlps["en"] = spacy.load("en_core_web_sm")
    except ModuleNotFoundError:
        os.system("python3 -m spacy download de_core_news_sm")
        os.system("python3 -m spacy download en_core_web_sm")


def read_tokens():
    '''reads in the tokens from a json-file generated by the java part

    '''

    file = open("jcasson.json")
    dic = json.load(file)

    return (dic["text"], dic["lang"])


def process(data):
    check_packages()
    text, lang = data.text, data.lang

    nlps = {}
    nlps["de"] = spacy.load("de_core_news_sm")
    nlps["en"] = spacy.load("en_core_web_sm")

    if lang in nlps:
        nlp = nlps[lang]
    else:
        nlp = nlps["en"]

    data = nlp(text)

    tokens = []
    sents = []
    pos = []
    deps = []
    ents = []

    for token in data:
        tokens_dict = {'idx': token.idx,
                       'length': len(token),
                       'is_space': token.is_space,
                       'token_text': token.text}
        tokens.append(tokens_dict)

        pos_dict = {'tag': token.tag_,
                    'idx': token.idx,
                    'length': len(token),
                    'is_space': token.is_space
                    }
        pos.append(pos_dict)

        deps_dict = {'dep': token.dep_,
                     'idx': token.idx,
                     'length': len(token),
                     'is_space': token.is_space,
                     'head': {'idx': token.head.idx,
                              'length': len(token.head),
                              'is_space': token.head.is_space
                              }
                     }
        deps.append(deps_dict)

    for sent in data.sents:
        sents_dict = {'begin': sent.start_char,
                      'end': sent.end_char}
        sents.append(sents_dict)

    for ent in data.ents:
        ents_dict = {'start_char': ent.start_char,
                      'end_char': ent.end_char,
                      'label': ent.label_
                      }
        ents.append(ents_dict)

    return tokens, sents, pos, deps, ents


if __name__ == '__main__':
    app = FastAPI()

    class JavaData(BaseModel):
        text: str
        lang: str

    @app.post("/data/")
    def read_from_java(data: JavaData):
        print(data.text)
        print(data.lang)
        return process(data)

    uvicorn.run(app)
