FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8000

# disable torch gpu
ENV CUDA_VISIBLE_DEVICES=

COPY ./supar_service.py ./supar_service.py

CMD ["uvicorn", "supar_service:app", "--host", "0.0.0.0", "--port" ,"8000"]