FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

RUN python -m textblob.download_corpora
RUN python -m nltk.downloader punkt

EXPOSE 8000

COPY ./textblob_service.py ./textblob_service.py

CMD ["uvicorn", "textblob_service:app", "--host", "0.0.0.0", "--port" ,"8000"]