FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

RUN python3 -m spacy download de_core_news_sm
RUN python3 -m spacy download en_core_web_sm

EXPOSE 8000

COPY ./spacy_multi_tagger.py ./spacy_multi_tagger.py

CMD ["spacy_multi_tagger.py"]
ENTRYPOINT ["python3"]