FROM python:3.8

WORKDIR /usr/src/app

COPY ./gervader ./gervader

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8000

COPY ./gervader_service.py ./gervader_service.py

CMD ["uvicorn", "gervader_service:app", "--host", "0.0.0.0", "--port" ,"8000"]