FROM python:3.8

WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8000

# TODO disabled gpu, not working locally
ENV CUDA_VISIBLE_DEVICES=

# preload models during docker build
COPY ./german_sentiment_bert_preload_models.py ./german_sentiment_bert_preload_models.py
RUN ["python3", "german_sentiment_bert_preload_models.py"]

COPY ./german_sentiment_bert_service.py ./german_sentiment_bert_service.py

CMD ["uvicorn", "german_sentiment_bert_service:app", "--host", "0.0.0.0", "--port" ,"8000"]