FROM python:3.8

WORKDIR /usr/src/app

RUN pip install setuptools wheel

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8000

# preload models
RUN python -m spacy download ca_core_news_sm
RUN python -m spacy download zh_core_web_sm
RUN python -m spacy download da_core_news_sm
RUN python -m spacy download nl_core_news_sm
RUN python -m spacy download en_core_web_sm
RUN python -m spacy download fr_core_news_sm
RUN python -m spacy download de_core_news_sm
RUN python -m spacy download el_core_news_sm
RUN python -m spacy download it_core_news_sm
RUN python -m spacy download ja_core_news_sm
RUN python -m spacy download lt_core_news_sm
RUN python -m spacy download mk_core_news_sm
RUN python -m spacy download xx_ent_wiki_sm
RUN python -m spacy download nb_core_news_sm
RUN python -m spacy download pl_core_news_sm
RUN python -m spacy download pt_core_news_sm
RUN python -m spacy download ro_core_news_sm
RUN python -m spacy download ru_core_news_sm
RUN python -m spacy download es_core_news_sm
# accuracy
RUN python -m spacy download ca_core_news_trf
RUN python -m spacy download zh_core_web_trf
RUN python -m spacy download da_core_news_trf
RUN python -m spacy download nl_core_news_lg
RUN python -m spacy download en_core_web_trf
RUN python -m spacy download fr_dep_news_trf
RUN python -m spacy download de_dep_news_trf
RUN python -m spacy download el_core_news_lg
RUN python -m spacy download it_core_news_lg
RUN python -m spacy download ja_core_news_lg
RUN python -m spacy download lt_core_news_lg
RUN python -m spacy download mk_core_news_lg
RUN python -m spacy download xx_sent_ud_sm
RUN python -m spacy download nb_core_news_lg
RUN python -m spacy download pl_core_news_lg
RUN python -m spacy download pt_core_news_lg
RUN python -m spacy download ro_core_news_lg
RUN python -m spacy download ru_core_news_lg
RUN python -m spacy download es_dep_news_trf


ENV TEXTIMAGER_SPACY_USE_GPU=False

COPY ./spacy3_service.py ./spacy3_service.py

ENTRYPOINT ["uvicorn", "spacy3_service:app", "--host", "0.0.0.0", "--port" ,"8000"]
CMD ["--workers", "1"]
